### PR TITLE
added support for href="//xxxxx.onion/path/to/file.php" URLs

### PR DESCRIPTION
**Pull request by virgil**
I do a non-matching group for the http/https so that everything else stays the same as the previous regex.

### CODE REVIEW

**Comment by evilaliv3** [comment]
@virgil can you please explain better the reason of this pull request?

**Comment by virgil** [comment]
I want to rewrite addresses like action="//xxxxxxx.onion/path/to/file.php"

Because these days you can use the // without the http://.  Prior to this page the URLs beginning with a mere // didn't work.

**Comment by evilaliv3** [comment]
i see. good patch, i've retested it and it implements what you say! :)

**Comment by evilaliv3** [comment]
integrated manually.

**Pull request closed without merging**
